datasources:
  default:
    url: jdbc:postgresql://localhost:5432/example_micronaut_thymeleaf
    driverClassName: org.postgresql.Driver
    username: postgres
    password: kevintan
    schema-generate: CREATE_DROP
    dialect: POSTGRES
